// =============================================================================
// reconciliationSchedule.js — embedded snapshot of SCHEDULE (4).xlsx (active jobs)
// =============================================================================
// ONE-TIME reconciliation source of truth. Parsed from the 3 active tabs (THE
// LATEST sections + INSCRIPTIONS, with HALL MONUMENTS + "HM " vendor stock
// excluded and FDN folded in as foundation status). ${jobs.length} active jobs.
// Regenerate only if the schedule file changes. Reference data — no live coupling.
// =============================================================================

export const RECONCILIATION_BATCH = { file: 'SCHEDULE (4).xlsx', jobCount: 92 }
export const RECONCILIATION_SCHEDULE = [
  {
    "id": "sch-1",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "HERNANDEZ, J.",
    "surname": "HERNANDEZ",
    "firstInitial": "J",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-2",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "HOLLIS",
    "surname": "HOLLIS",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-3",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "AVILES",
    "surname": "AVILES",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "NO",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-4",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "FELICIANO",
    "surname": "FELICIANO",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-5",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "DE LA CRUZ",
    "surname": "DE LA CRUZ",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-6",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "STEINLAUF",
    "surname": "STEINLAUF",
    "firstInitial": "",
    "cemeteryRaw": "BETH ISRAEL",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-7",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "NIEMIERA",
    "surname": "NIEMIERA",
    "firstInitial": "",
    "cemeteryRaw": "CALVARY",
    "paid": "NO",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-8",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "BOLL",
    "surname": "BOLL",
    "firstInitial": "",
    "cemeteryRaw": "HOLY CROSS",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-9",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "TREVENA",
    "surname": "TREVENA",
    "firstInitial": "",
    "cemeteryRaw": "HOLY TRINITY",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "2-8 X 1-0",
    "fdnDue": "3/6",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-10",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "MIRABALLES",
    "surname": "MIRABALLES",
    "firstInitial": "",
    "cemeteryRaw": "MAPLEWOOD",
    "paid": "NO",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-11",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "DEFOE",
    "surname": "DEFOE",
    "firstInitial": "",
    "cemeteryRaw": "WASHINGTON MEMORIAL",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "READY",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "READY",
    "pause": false
  },
  {
    "id": "sch-12",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "SITUMEANG",
    "surname": "SITUMEANG",
    "firstInitial": "",
    "cemeteryRaw": "FIRST PRES",
    "paid": "NO",
    "paidDate": "",
    "stoneStatus": "CUT",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "CUT",
    "pause": false
  },
  {
    "id": "sch-13",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "FIETCHER MKR",
    "surname": "FIETCHER",
    "firstInitial": "",
    "cemeteryRaw": "HOLLYWOOD",
    "paid": "NO",
    "paidDate": "",
    "stoneStatus": "CUT",
    "cutStatus": "",
    "fdnStatus": "DROP OFF",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "CUT",
    "pause": false
  },
  {
    "id": "sch-14",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "VASS",
    "surname": "VASS",
    "firstInitial": "",
    "cemeteryRaw": "CHRIST CHURCH",
    "paid": "NO",
    "paidDate": "",
    "stoneStatus": "CUT",
    "cutStatus": "",
    "fdnStatus": "NO",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "CUT",
    "pause": false
  },
  {
    "id": "sch-15",
    "section": "LATEST STONES",
    "type": "new_stone",
    "nameRaw": "LAZAURS",
    "surname": "LAZAURS",
    "firstInitial": "",
    "cemeteryRaw": "BAYVIEW LEONARDO",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "CUT",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "CUT",
    "pause": false
  },
  {
    "id": "sch-16",
    "section": "ACID WASHES",
    "type": "acid_wash",
    "nameRaw": "KOYEN",
    "surname": "KOYEN",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "11/19",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-17",
    "section": "ACID WASHES",
    "type": "acid_wash",
    "nameRaw": "DOUGALA",
    "surname": "DOUGALA",
    "firstInitial": "",
    "cemeteryRaw": "HILLSIDE",
    "paid": "PAID",
    "paidDate": "10/16",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-18",
    "section": "ACID WASHES",
    "type": "acid_wash",
    "nameRaw": "STEINLAUF",
    "surname": "STEINLAUF",
    "firstInitial": "",
    "cemeteryRaw": "BETH ISRAEL",
    "paid": "PAID",
    "paidDate": "3/13",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-19",
    "section": "ACID WASHES",
    "type": "acid_wash",
    "nameRaw": "SOKOLOFF",
    "surname": "SOKOLOFF",
    "firstInitial": "",
    "cemeteryRaw": "FAIRVIEW WF",
    "paid": "NOT PAID",
    "paidDate": "6/4",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "NOT CUT",
    "pause": false
  },
  {
    "id": "sch-20",
    "section": "ACID WASHES",
    "type": "acid_wash",
    "nameRaw": "PERFINOWICZ",
    "surname": "PERFINOWICZ",
    "firstInitial": "",
    "cemeteryRaw": "HILLSIDE MET",
    "paid": "PAID",
    "paidDate": "4/17",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "ACID WASH",
    "pause": false
  },
  {
    "id": "sch-21",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "LIPOWITZ",
    "surname": "LIPOWITZ",
    "firstInitial": "",
    "cemeteryRaw": "BETH ISRAEL",
    "paid": "PAID",
    "paidDate": "3/26",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-22",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "CYKTOR",
    "surname": "CYKTOR",
    "firstInitial": "",
    "cemeteryRaw": "SAINT GERTRUDE",
    "paid": "PAID",
    "paidDate": "10/31",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "CHELSEA",
    "pause": false
  },
  {
    "id": "sch-23",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "GEROW",
    "surname": "GEROW",
    "firstInitial": "",
    "cemeteryRaw": "SAINT GERTRUFE",
    "paid": "",
    "paidDate": "ASAP",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-24",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "YANVARY",
    "surname": "YANVARY",
    "firstInitial": "",
    "cemeteryRaw": "ST JAMES",
    "paid": "PAID",
    "paidDate": "6/2",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "FDN ROW",
    "fdnSize": "FDN RECAP STONE & BENCH",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-25",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "RYNAGA",
    "surname": "RYNAGA",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "DREMIL",
    "pause": false
  },
  {
    "id": "sch-26",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "WITKIN",
    "surname": "WITKIN",
    "firstInitial": "",
    "cemeteryRaw": "BETH MORDECAI",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "CHELSEA",
    "pause": false
  },
  {
    "id": "sch-27",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "KUCHIRKA",
    "surname": "KUCHIRKA",
    "firstInitial": "",
    "cemeteryRaw": "UKR",
    "paid": "",
    "paidDate": "3/25",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-28",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "DOBROWOLSKI",
    "surname": "DOBROWOLSKI",
    "firstInitial": "",
    "cemeteryRaw": "ST JAMES",
    "paid": "PAID",
    "paidDate": "3/10",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-29",
    "section": "REPAIR JOBS",
    "type": "repair",
    "nameRaw": "TREE STUMP REMOVAL",
    "surname": "TREE STUMP REMOVAL",
    "firstInitial": "",
    "cemeteryRaw": "ST JAMES",
    "paid": "PAID",
    "paidDate": "9/12",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "LONNIE DO THIS",
    "pause": false
  },
  {
    "id": "sch-30",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "CORDEIRO",
    "surname": "CORDEIRO",
    "firstInitial": "",
    "cemeteryRaw": "GRACELAND",
    "paid": "????",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-31",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "MARTIN",
    "surname": "MARTIN",
    "firstInitial": "",
    "cemeteryRaw": "FOREST GREEN",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-32",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "RODRIGUEZ",
    "surname": "RODRIGUEZ",
    "firstInitial": "",
    "cemeteryRaw": "FOREST GREEN",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-33",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "LAWRENCE",
    "surname": "LAWRENCE",
    "firstInitial": "",
    "cemeteryRaw": "ROSEDALE",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-34",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "FLEXSER",
    "surname": "FLEXSER",
    "firstInitial": "",
    "cemeteryRaw": "MT LEB",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-35",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "BAR-DIN",
    "surname": "BAR-DIN",
    "firstInitial": "",
    "cemeteryRaw": "MT LEB",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "WAIT TILL DEATH",
    "pause": true
  },
  {
    "id": "sch-36",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "GRABER REICHENBAUM",
    "surname": "GRABER REICHENBAUM",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-37",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "LEVY",
    "surname": "LEVY",
    "firstInitial": "",
    "cemeteryRaw": "FLORAL PARK",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "WAIT TILL DEATH",
    "pause": true
  },
  {
    "id": "sch-38",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "VARGAS",
    "surname": "VARGAS",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "DOES NOT HAVE $",
    "pause": true
  },
  {
    "id": "sch-39",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "BODNICK",
    "surname": "BODNICK",
    "firstInitial": "",
    "cemeteryRaw": "BETH ISRAEL",
    "paid": "PAID",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-40",
    "section": "BRONZE/DROP OFF",
    "type": "bronze",
    "nameRaw": "ABER",
    "surname": "ABER",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "FDN IN",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-41",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "MELO",
    "surname": "MELO",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-42",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "BRAND SLT",
    "surname": "BRAND",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-43",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "SHMULER",
    "surname": "SHMULER",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-44",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "MAGYAR SLT",
    "surname": "MAGYAR",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-45",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "KISHINEVSKY",
    "surname": "KISHINEVSKY",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "CUT",
    "pause": false
  },
  {
    "id": "sch-46",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "ROMOV SLT",
    "surname": "ROMOV",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-47",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "MATO",
    "surname": "MATO",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-48",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "FERNANDEZ",
    "surname": "FERNANDEZ",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-49",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "LEONARD",
    "surname": "LEONARD",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-50",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "D'ANGELO",
    "surname": "D'ANGELO",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-51",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "ROSARIO",
    "surname": "ROSARIO",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "FDN ROW",
    "fdnSize": "2-0 X 1-0 MRK",
    "fdnDue": "5/4",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-52",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "BLUE FLAT",
    "surname": "BLUE FLAT",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-53",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "CLARK",
    "surname": "CLARK",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "FDN ROW",
    "fdnSize": "2-6 X 1-0",
    "fdnDue": "3/31",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-54",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "GETZ",
    "surname": "GETZ",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-55",
    "section": "NEXT LINE UP",
    "type": "new_stone",
    "nameRaw": "RUSSOMANNO",
    "surname": "RUSSOMANNO",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-56",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "PAVLAKOS",
    "surname": "PAVLAKOS",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "4/10",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-57",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "TARR",
    "surname": "TARR",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "5/2",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-58",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "PARIDES",
    "surname": "PARIDES",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "6/3",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-59",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SOTO",
    "surname": "SOTO",
    "firstInitial": "",
    "cemeteryRaw": "ALPINE",
    "paid": "PAID",
    "paidDate": "BY MAY",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "PERMIT",
    "pause": false
  },
  {
    "id": "sch-60",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "FLYNN",
    "surname": "FLYNN",
    "firstInitial": "",
    "cemeteryRaw": "christ church",
    "paid": "PAID",
    "paidDate": "5/29",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-61",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SOKOLOFF",
    "surname": "SOKOLOFF",
    "firstInitial": "",
    "cemeteryRaw": "FAIRVIEW WF",
    "paid": "NOT PAID",
    "paidDate": "6/4",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-62",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "KOPEK",
    "surname": "KOPEK",
    "firstInitial": "",
    "cemeteryRaw": "HOLY TRINITY",
    "paid": "PAID",
    "paidDate": "5/1",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-63",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "KOBALA",
    "surname": "KOBALA",
    "firstInitial": "",
    "cemeteryRaw": "HOLY TRINITY",
    "paid": "PAID",
    "paidDate": "5/28",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-64",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "LEONARD",
    "surname": "LEONARD",
    "firstInitial": "",
    "cemeteryRaw": "HOLY TRINITY",
    "paid": "PAID",
    "paidDate": "6/10",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-65",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SIEWARGA PAPPACHRISTUS",
    "surname": "SIEWARGA PAPPACHRISTUS",
    "firstInitial": "",
    "cemeteryRaw": "HOLY TRINITY",
    "paid": "PAID",
    "paidDate": "6/12",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-66",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "CAPIK",
    "surname": "CAPIK",
    "firstInitial": "",
    "cemeteryRaw": "HOLY TRINITY",
    "paid": "PAID",
    "paidDate": "5/20",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-67",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SOLTYS",
    "surname": "SOLTYS",
    "firstInitial": "",
    "cemeteryRaw": "MT CALVARY",
    "paid": "PAID",
    "paidDate": "5/18",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-68",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "ZOILO",
    "surname": "ZOILO",
    "firstInitial": "",
    "cemeteryRaw": "NEW MT LEB",
    "paid": "PAID",
    "paidDate": "4/13",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-69",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "GUZMAN",
    "surname": "GUZMAN",
    "firstInitial": "",
    "cemeteryRaw": "OLH",
    "paid": "HALF",
    "paidDate": "4/25",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "FDN ROW",
    "fdnSize": "3-0 X 1-0",
    "fdnDue": "4-22",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-70",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SYMANSKI",
    "surname": "SYMANSKI",
    "firstInitial": "",
    "cemeteryRaw": "OLH",
    "paid": "PAID",
    "paidDate": "6/4",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-71",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "GRACE LUTHERAN CHURCH",
    "surname": "GRACE LUTHERAN CHURCH",
    "firstInitial": "",
    "cemeteryRaw": "PICK UP",
    "paid": "PAID",
    "paidDate": "BY JULY 5TH",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "BY JULY 5TH",
    "pause": false
  },
  {
    "id": "sch-72",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "KOVACS",
    "surname": "KOVACS",
    "firstInitial": "",
    "cemeteryRaw": "RESURRECTION PISC",
    "paid": "PAID",
    "paidDate": "4/22",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-73",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "KOSOVSKIY",
    "surname": "KOSOVSKIY",
    "firstInitial": "",
    "cemeteryRaw": "ROSEDALE",
    "paid": "PAID",
    "paidDate": "6/8",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-74",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "CASTRO",
    "surname": "CASTRO",
    "firstInitial": "",
    "cemeteryRaw": "ROSEHILL",
    "paid": "PAID",
    "paidDate": "3/11",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-75",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "CYGAN",
    "surname": "CYGAN",
    "firstInitial": "",
    "cemeteryRaw": "SACRED HEART",
    "paid": "PAID",
    "paidDate": "4/16",
    "stoneStatus": "",
    "cutStatus": "HALF",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-76",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "RAY",
    "surname": "RAY",
    "firstInitial": "",
    "cemeteryRaw": "SACRED HEART",
    "paid": "PAID",
    "paidDate": "4/16",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-77",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "ZSAK",
    "surname": "ZSAK",
    "firstInitial": "",
    "cemeteryRaw": "SACRED HEART",
    "paid": "PAID",
    "paidDate": "5/30",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-78",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SIGMUND",
    "surname": "SIGMUND",
    "firstInitial": "",
    "cemeteryRaw": "SACRED HEART",
    "paid": "PAID",
    "paidDate": "6/8",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-79",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SCHAPOWAL",
    "surname": "SCHAPOWAL",
    "firstInitial": "",
    "cemeteryRaw": "SAINT ANDREW",
    "paid": "PAID",
    "paidDate": "5/14",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-80",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "ZAMORSKI",
    "surname": "ZAMORSKI",
    "firstInitial": "",
    "cemeteryRaw": "SAINT GERTRUDE",
    "paid": "PAID",
    "paidDate": "4/19",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-81",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "TAYLOR",
    "surname": "TAYLOR",
    "firstInitial": "",
    "cemeteryRaw": "SAINT GERTRUDE",
    "paid": "PAID",
    "paidDate": "4/22",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-82",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "SHEPHERD",
    "surname": "SHEPHERD",
    "firstInitial": "",
    "cemeteryRaw": "SAINT GERTRUDE",
    "paid": "PAID",
    "paidDate": "4/28",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-83",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "MCDONALD",
    "surname": "MCDONALD",
    "firstInitial": "",
    "cemeteryRaw": "SAINT GERTRUDE",
    "paid": "NO YET",
    "paidDate": "5/30",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-84",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "MAREK",
    "surname": "MAREK",
    "firstInitial": "",
    "cemeteryRaw": "SAINT NIC",
    "paid": "PAID",
    "paidDate": "5/8",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-85",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "HUGHES",
    "surname": "HUGHES",
    "firstInitial": "",
    "cemeteryRaw": "ST GERTS",
    "paid": "PAID",
    "paidDate": "4/20",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-86",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "KOLIBAS /SICA / CALANTONI",
    "surname": "KOLIBAS",
    "firstInitial": "",
    "cemeteryRaw": "ST JAMES",
    "paid": "PAID",
    "paidDate": "BY JULY 10TH",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-87",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "DELARATO",
    "surname": "DELARATO",
    "firstInitial": "",
    "cemeteryRaw": "ST PETER AND PAUL",
    "paid": "PAID",
    "paidDate": "6/4",
    "stoneStatus": "",
    "cutStatus": "NOT CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-88",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "GADEK",
    "surname": "GADEK",
    "firstInitial": "",
    "cemeteryRaw": "UKR",
    "paid": "PAID",
    "paidDate": "5/14",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-89",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "PACOLAK",
    "surname": "PACOLAK",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "PAID",
    "paidDate": "5/4",
    "stoneStatus": "",
    "cutStatus": "",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-90",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "BACHLEDA",
    "surname": "BACHLEDA",
    "firstInitial": "",
    "cemeteryRaw": "",
    "paid": "",
    "paidDate": "",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "DOUBLE CHECK - GUESSED SIZE",
    "pause": false
  },
  {
    "id": "sch-91",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "BRODERICK",
    "surname": "BRODERICK",
    "firstInitial": "",
    "cemeteryRaw": "ST GABRIEL MARLBORO",
    "paid": "NOT PAID",
    "paidDate": "4/15",
    "stoneStatus": "",
    "cutStatus": "CUT",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  },
  {
    "id": "sch-92",
    "section": "INSCRIPTIONS",
    "type": "inscription",
    "nameRaw": "PERFINOWICZ",
    "surname": "PERFINOWICZ",
    "firstInitial": "",
    "cemeteryRaw": "HILLSIDE MET",
    "paid": "PAID",
    "paidDate": "4/17",
    "stoneStatus": "",
    "cutStatus": "ACID WASH",
    "fdnStatus": "",
    "fdnSize": "",
    "fdnDue": "",
    "opNote": "",
    "pause": false
  }
]
